// ignore_for_file: constant_identifier_names
const USER_DATA = 'USER_DATA';
const USER_SESSION_TOKEN = 'USER_SESSION_TOKEN';
const USER_REMEMBER_ME_EMAIL = 'USER_REMEMBER_ME_EMAIL';
const USER_REMEMBER_ME_PASS = 'USER_REMEMBER_ME_PASS';
const USER_REMEMBER_ME_ENABLED = 'USER_REMEMBER_ME_ENABLED';
const USER_BIOMETRIC_ENABLED = 'USER_FINGERPRINT_BIOMETRIC';
const USER_BIOMETRIC_EMAIL = 'USER_FINGERPRINT_BIOMETRIC_EMAIL';
const USER_BIOMETRIC_NAME = 'USER_FINGERPRINT_BIOMETRIC_NAME';
const HIDE_AUTH_ONBOARDING_SCREEN = 'HIDE_AUTH_ONBOARDING_SCREEN';
